# Generated by Django 4.0.5 on 2022-06-30 07:59

from django.db import migrations, models
import djongo.models.fields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=150, null=True)),
                ('username', models.CharField(max_length=25)),
                ('phoneno', models.CharField(max_length=10)),
                ('extension', models.CharField(max_length=3)),
                ('location', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=6)),
                ('associations', djongo.models.fields.EmbeddedField(blank=True, model_container=users.models.Associations, null=True)),
                ('active', models.BooleanField(default=False)),
                ('published', djongo.models.fields.EmbeddedField(blank=True, model_container=users.models.Articles, null=True)),
                ('liked_article', djongo.models.fields.EmbeddedField(blank=True, model_container=users.models.Articles, null=True)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
    ]
