# Generated by Django 3.2.14 on 2022-07-06 05:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields
import users.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=150, null=True)),
                ('username', models.CharField(max_length=25)),
                ('phoneno', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='', regex='^\\+?1?\\d{9,15}$')])),
                ('location', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Male', max_length=6)),
                ('associations', djongo.models.fields.EmbeddedField(blank=True, model_container=users.models.Associations, null=True)),
                ('active', models.BooleanField(default=True)),
                ('published', djongo.models.fields.EmbeddedField(blank=True, model_container=users.models.Articles, null=True)),
                ('liked_article', djongo.models.fields.EmbeddedField(blank=True, model_container=users.models.Articles, null=True)),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='The time at which the first visit of the day was recorded')),
                ('session_key', models.CharField(help_text='Django session identifier', max_length=40)),
                ('remote_addr', models.CharField(blank=True, help_text='Client IP address (from X-Forwarded-For HTTP header, or REMOTE_ADDR request property)', max_length=100)),
                ('ua_string', models.TextField(blank=True, help_text='Client User-Agent HTTP header', verbose_name='User agent (raw)')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hash', models.CharField(help_text='MD5 hash generated from request properties', max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time at which the database record was created (!=timestamp)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
